cities:
  path: api/cities
  controller: App\Application\REST\City\Collection\GET
  methods: GET

city_get:
  path: api/cities/{id}
  controller: App\Application\REST\City\Resource\GET
  methods: GET

city_post:
  path: api/cities
  controller: App\Application\REST\City\Resource\POST
  methods: POST

city_patch:
  path: api/cities/{id}
  controller: App\Application\REST\City\Resource\PATCH
  methods: PATCH

city_delete:
  path: api/cities/{id}
  controller: App\Application\REST\City\Resource\DELETE
  methods: DELETE

stations:
  path: api/stations
  controller: App\Application\REST\Station\Collection\GET
  methods: GET

station_get:
  path: api/stations/{id}
  controller: App\Application\REST\Station\Resource\GET
  methods: GET

station_post:
  path: api/stations
  controller: App\Application\REST\Station\Resource\POST
  methods: POST

station_patch:
  path: api/stations/{id}
  controller: App\Application\REST\Station\Resource\PATCH
  methods: PATCH

station_delete:
  path: api/stations/{id}
  controller: App\Application\REST\Station\Resource\DELETE
  methods: DELETE

dock_post:
  path: api/docks
  controller: App\Application\REST\Dock\Resource\POST
  methods: POST

dock_patch:
  path: api/docks/{id}
  controller: App\Application\REST\Dock\Resource\PATCH
  methods: PATCH
