parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Application\REST\:
        resource: '%kernel.project_dir%/src/Application/REST'
        tags:
            - controller.service_arguments

    App\Domain\UseCase\:
        tags:
            - messenger.message_handler
        resource: '%kernel.project_dir%/src/Domain/UseCase/**/Handler.php'

    App\Infrastructure\Symfony\Messenger\MessageBus: ~

    App\Application\MessageBus: '@App\Infrastructure\Symfony\Messenger\MessageBus'

    App\Infrastructure\Doctrine\Repository\:
        resource: '%kernel.project_dir%/src/Infrastructure/Doctrine/Repository/*.php'

    App\Domain\Data\Collection\Cities: '@App\Infrastructure\Doctrine\Repository\CityRepository'
    App\Domain\Data\Collection\Docks: '@App\Infrastructure\Doctrine\Repository\DockRepository'
    App\Domain\Data\Collection\Stations: '@App\Infrastructure\Doctrine\Repository\StationRepository'
