version: 2
updates:
  - package-ecosystem: composer
    directory: ./apps/api
    labels:
      - dependencies
      - 'PHP'
    commit-message:
      prefix: chore
    schedule:
      interval: weekly
      day: monday
      time: '07:00'
      timezone: Europe/Paris
    open-pull-requests-limit: 3
    allow:
      - dependency-name: 'symfony/*'
      - dependency-name: 'webmozart/assert'
    groups:
      symfony:
        update-types:
          - 'minor'
        patterns:
          - 'symfony/*'

  - package-ecosystem: docker
    directory: ./apps/api 
    labels:
      - dependencies
      - 'Dockerfile'
    commit-message:
      prefix: chore
    schedule:
      interval: weekly
      day: monday
      time: '07:00'
      timezone: Europe/Paris
    open-pull-requests-limit: 3
    allow:
      - dependency-name: 'composer'
