---
version: '3.8'

services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    volumes:
      - './apps/api:/usr/src/app'

  nginx:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
      target: nginx
    depends_on:
      - api
    ports:
      - '80:80'

  db:
    image: mysql:8.0.32
    restart: on-failure
    environment:
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_DATABASE=database'
      - 'MYSQL_USER=test'
      - 'MYSQL_PASSWORD=test'
    volumes:
      - 'db:/var/lib/mysql'

volumes:
  db: ~