---
version: '3.8'

services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    volumes:
      - './apps/api:/usr/src/app'

  nginx:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
      target: nginx
    depends_on:
      - api
    ports:
      - '80:80'